version: '3.7'
services:
  golr:
    hostname: golr 
    container_name: golr 
    image: {{ amigo_image }}
    init: true
    environment:
      - GOLR=1
      - AMIGO=0
      - GOLR_SOLR_MEMORY={{ GOLR_SOLR_MEMORY }}
    volumes:
      - {{ stage_dir }}/golr-configs/java-golr-monit:/etc/monit/conf-enabled/java
      - {{ stage_dir }}/golr-configs/console-capture-golr.xml:/etc/jetty9/console-capture.xml
      - {{ stage_dir }}/srv-solr-data:/srv/solr/data
      - {{ stage_dir }}/golr_logs:/var/log
    restart: unless-stopped
    healthcheck:
       test: wget --no-verbose --timeout=5 --tries=5 --spider http://golr:8080 || kill 1
       interval: 60s
       retries: 1
       start_period: 30s

  amigo:
    hostname: amigo
    container_name: amigo
    image: {{ amigo_image }}
    init: true
    environment:
      - GOLR=0
      - AMIGO=1
    volumes:
      - {{ repo_dir }}:/srv/amigo
      - {{ stage_dir }}/amigo_working_path:/tmp
      - {{ stage_dir }}/golr_timestamp.log:/tmp/golr_timestamp.log
      - {{ stage_dir }}/release-archive-doi.json:/tmp/release-archive-doi.json
      - {{ stage_dir }}/amigo-configs/amigo.yaml:/srv/amigo/conf/amigo.yaml.orig
      - {{ stage_dir }}/amigo-configs/001-inline-amigo.conf:/etc/apache2/sites-available/001-inline-amigo.conf
      - {{ stage_dir }}/amigo-configs/apache2.ports.conf:/etc/apache2/ports.conf
      - {{ stage_dir }}/apache_amigo_logs:/var/log/apache2
    restart: unless-stopped
    # Needs investigation: The server starts after a fresh install in about 90 seconds. But somehow it gets killed 
    # after 60 seconds even though we set the start period to 300 seconds.
    # healthcheck:
    #   test: wget --no-verbose --timeout=5 --tries=5 --spider http://amigo:9999 || kill 1
    #   interval: 60s
    #   retries: 1
    #   start_period: 300s
    depends_on:
      - golr 

  apache_amigo:
    hostname: apache_amigo
    container_name: apache_amigo
    image: {{ apache_proxy_image }}
    init: true
    restart: unless-stopped
    environment:
      - USE_S3={{ USE_S3 }}
      - S3_PATH={{ S3_PATH }}
      - S3_BUCKET={{ S3_BUCKET }}
      - USE_SSL={{ USE_SSL }}
      - S3_SSL_CERTS_LOCATION={{ S3_SSL_CERTS_LOCATION }}
      - USE_CLOUDFLARE={{ USE_CLOUDFLARE }}
    volumes:
      - {{ stage_dir }}/proxy-configs:/etc/apache2/sites-enabled
      - {{ stage_dir }}/apache_proxy_logs:/var/log/apache2
      - {{ stage_dir }}/credentials:/opt/credentials
      - {{ stage_dir }}/proxy-configs/s3cfg:/root/.aws/config
      - {{ stage_dir }}/qos.conf:/etc/apache2/mods-enabled/qos.conf
      - {{ stage_dir }}/robots.txt:/var/www/html/robots.txt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - golr 
      - amigo
