####
#### AmiGO variables for installation.
####
---
AMIGO_CONFIGURED:
  value: 0
  comment: >
    This variable must be edited (to 1) before installing AmiGO.
  type: boolean
  
###
### Path and binary variables.
###

AMIGO_ROOT:
  value: ''
  comment: >
    Please enter the full path to the git repo amigo[/trunk] directory.
  type: directory
    
GO_YAML_LOCATION:
  value: ''
  comment: >
    Please enter the full path to the YAML config files directory. In that directory, all files like *config.yaml will be scanned for use.
  type: directory

GO_BBOPJS_LOCATION:
  comment: >
    If this is not redefined to a new location (e.g. the BBOP-JS staging/ directory, it will use the bbop.js bundle packaged with AmiGO 2 (the one used in the unit tests) in the _data/ directory.
  type: directory
  value: ./_data

# - NAME: AMIGO_DOT_PATH
#   value: /usr/bin/dot
#   comment: "Please enter the full path for the \"dot\" command"
#   type: executable

###
### AmiGO mapping variables.
###

AMIGO_PROJECT_NAME:
  value: amigo2
  comment: Please enter the name of this AmiGO installation.
  type: string
    
AMIGO_HTDOCS_PARTIAL_PATH:
  value: /srv/www/htdocs
  comment: Please enter the full path to a usable static document directory.
  type: directory

AMIGO_HTDOCS_PARTIAL_URL:
  value: http://localhost
  comment: Please enter the URL that this path maps to.
  type: url

AMIGO_CGI_PARTIAL_PATH:
  value: /srv/www/cgi-bin
  comment: Please enter the full path to a usable CGI enabled directory.
  type: directory

AMIGO_CGI_PARTIAL_URL:
  value: http://localhost/cgi-bin
  comment: Please enter the URL that this path maps to.
  type: url

AMIGO_PUBLIC_CGI_PARTIAL_URL:
  value: http://amigo.geneontology.org/cgi-bin
  comment: Please enter the partial public URL.
  type: true

AMIGO_PUBLIC_GOLR_URL:
  value: http://localhost:8080/solr/
  comment: Please enter the public URL of the GOlr server.
  type: url

AMIGO_PUBLIC_GALAXY_URL:
  value: http://galaxy.berkeleybop.org/
  comment: Please enter the public URL of the Galaxy server.
  type: url

###
### AmiGO internal variables.
###

AMIGO_SHOW_GOOSE_LINKS:
  value: 1
  comment: >
    Do you wish to show links to GOOSE, the GO Online SQL Environment?

    Note that this is only suitable for if you are installing the
    GO GOLD database.

    Use 1 for yes and 0 for no.
  type: boolean

AMIGO_TERM_REGEXP:
  value: all|GO:[0-9]{7}
  comment: The regular expressions to identify ontology ids.
  type: string

AMIGO_LAYOUT_LANDING:
  comment: A whitespace separated list of class IDs to use for searches on the landing page.
  type: string
  value: bbop_ont bbop_bio

AMIGO_LAYOUT_SEARCH:
  comment: A whitespace separated list of class IDs to use for live search tabs on the search page.
  type: string
  value: bbop_ann bbop_ont bbop_bio bbop_ann_ev_agg

AMIGO_VERBOSE:
  value: 0
  comment: Log verbose AmiGO debugging messages.
  type: boolean

AMIGO_TROUBLE_SWITCH:
  value: 0
  comment: Mark the AmiGO site as TROUBLED (triggers some changes).
  type: boolean

AMIGO_TROUBLE_MESSAGE:
  value: >
    <h2 style="text-align: center;">
    AmiGO is currently experiencing some difficulty.<br />
    You may want to temporarily try <a
    href="http://amigo.berkeleybop.org/cgi-bin/amigo/go.cgi"
    title="Go to AmiGO Labs">AmiGO Labs</a>
    instead.</h2>
  comment: "Message to present when AmiGO\'s TROUBLE switch is true."
  type: string

AMIGO_BETA:
  value: 0
  comment: >
    Mark the AmiGO site as BETA (triggers some changes in
    variables and installed features).
  type: boolean

AMIGO_VERSION:
  value: 2.0
  comment: Displayed AmiGO version string.
  type: string

AMIGO_JS_VERSION:
  value: 0.9
  comment: The version to apply to the JS bundle creation (should match BBOP-JS).
  type: string

AMIGO_GOOGLE_ANALYTICS_ID:
  value: ''
  comment: Google analytics ID. Optional.
  type: string
